# does only generate a new id when needed
# - name: SYNCTHING - Generate device id
#   command: syncthing -generate=/home/{{ common_user.name }}/.config/syncthing/
#   changed_when: false

# - name: SYNCTHING - Get syncthing device id
#   command: syncthing -device-id
#   register: syncthing_id
#   changed_when: false

# - name: SYNCTHING - Copy xml file
#   template:
#     src: syncthing_config.xml.j2
#     dest: /home/{{ common_user.name }}/.config/syncthing/config.xml
#     owner: "{{ common_user.name }}"
#     group: "{{ common_user.name }}"
#     mode: 0644

# - name: SYNCTHING - Enable & Start systemd service
#   systemd:
#     name: syncthing@{{ common_user.name }}
#     state: restarted
#     enabled: yes
#   become: true

# - name: symlink all directories to the home directory
#   shell: '{{ item }}'
#   args:
#     warn: false
#   loop:
#     - 'ln -sf /home/{{ common_user.name}}/.dotfiles/.* /home/{{ common_user.name }}'
#     - 'ln -sf /home/{{ common_user.name}}/.dotfiles/.config/* /home/{{ common_user.name}}/.config'
#   ignore_errors: yes
