# This is hard-coded to en_US.UTF-8 for now. If you want to change it, you'll need to modify the regex and line values.
- name: Configure locale.gen
  lineinfile:
    dest: /mnt/etc/locale.gen
    regexp: '{{ item.regex }}'
    line: '{{ item.line }}'
  loop:
    - {regex: en_US\.UTF-8 UTF-8, line: en_US.UTF-8 UTF-8}

- name: Create locale.conf
  copy:
    content: "LANG=en_US.UTF-8"
    dest: /mnt/etc/locale.conf

- name: Generate locales
  command: arch-chroot /mnt locale-gen
